### ISSUE TITLE
Error ' Invalid JSON RPC response: " ' when connect to local Ganache at 127.0.0.1:8545

### ISSUE THREAD

**Issue by ARyaskov** [austintgriffith/clevis#17]
Hi, Austin! Great project, this is what I've been looking for!

I try to connect to local Ganache GUI client running at http://127.0.0.1:8545 but got error ' Invalid JSON RPC response: " ' on every clevis command I've typed (e.g. clevis accounts).

But 'geth attach http://127.0.0.1:8545' works!

Software:

MacOS Mojave
Node.js 9.11.1
Docker 18.06
Ganache 1.2.2
Clevis image built from git sources today.

Terminal output: 
```
Users-MacBook-Pro-3:docker user$ docker run -ti --rm --name clevis --env network="http://127.0.0.1:8545"  -p 3000:3000 -p 8545:8545 -v ~/your-dapp-directory:/dapp clevis
Launching 🗜️ Clevis with network [ http://127.0.0.1:8545 ]...
Updating...
Updating Mocha and current gas/eth prices...
/usr/bin/mocha -> /usr/lib/node_modules/mocha/bin/mocha

/usr/bin/_mocha -> /usr/lib/node_modules/mocha/bin/_mocha

+ mocha@5.2.0
added 24 packages from 436 contributors in 6.967s

 >>> UPDATE

{
  "provider": "http://127.0.0.1:8545",
  "gasprice": 8.7,
  "ethprice": 210.444965046,
  "deploygas": 5500000,
  "xfergas": 1300000,
  "DEBUG": true,
  "USE_INFURA": false,
  "ROOT_FOLDER": "/dapp",
  "CRA_FOLDER": "./src",
  "TESTS_FOLDER": "tests",
  "CONTRACTS_FOLDER": "contracts"
}

Using external RPC network: http://127.0.0.1:8545
{ help: [],
  init: [],
  init2: [],
  version: [],
  update: [],
  upgrade: [],
  accounts: [],
  new: [ 'password' ],
  unlock: [ 'accountindex', 'password' ],
  send: [ 'amount', 'fromindex', 'toindex' ],
  sendTo: [ 'amount', 'fromindex', 'toaddress' ],
  balance: [ 'address' ],
  sign: [ 'string', 'accountindex', 'password' ],
  recover: [ 'string', 'signature' ],
  sha3: [ 'string' ],
  sendData: [ 'amount', 'fromindex', 'toaddress', 'data' ],
  create: [ 'contractname' ],
  compile: [ 'contractname' ],
  deploy: [ 'contractname', 'accountindex' ],
  explain: [ 'contractname' ],
  contract: 
   [ 'scriptname',
     'contractname',
     '[accountIndex]',
     '[contractArguments...]' ],
  test: [ 'testname' ],
  fromwei: [ 'amount', 'symbol' ],
  towei: [ 'amount', 'symbol' ],
  tohex: [ 'textstring' ],
  fromhex: [ 'hexstring' ],
  blockNumber: [],
  block: [ 'blocknumber' ],
  transaction: [ 'hash' ],
  build: [],
  start: [],
  upload: [ '[target]' ],
  invalidate: [ '[target]' ],
  mocha: [] }
 >>> VERSION
{ clevis: '0.0.97', web3: '1.0.0-beta.36' }
🗜️ Clevis:/dapp 🗜️ clevis accounts
 >>> ACCOUNTS
Reading Accounts...
(node:89) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/clevis/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/clevis/node_modules/web3-providers-http/src/index.js:87:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/clevis/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/clevis/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/clevis/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/clevis/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:89) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:89) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
🗜️ Clevis:/dapp 🗜️ 
```

What I doing wrong? 
Best regards.

**Comment by austintgriffith** [comment]
127.0.0.1 won't work because it's inside the container. Plus, the container
will bring up a ganache for you.

take a closer look at the docs under the video here:
https://github.com/austintgriffith/clevis

if you want to use clevis with your own external ganache fire it up with
something like:
ganache-cli -h 0.0.0.0 -p 8545

Then, when you run your container do something like:

docker run -ti --rm --name clevis --env network="http://10.0.0.107:8545" \
  -p 3000:3000 -p 8545:8545 -v ~/your-dapp-directory:/dapp austingriffith/clevis

But replace that 10.0.0.107 with your machines public ip address
